apiVersion: v1
kind: Service
metadata:
  name: grafana
  labels:
    app: ft_services
spec:
  type: LoadBalancer
  selector:
    app: ft_services
  ports:
  - name: grafana
    port: 3000
---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: grafana
spec:
  serviceName: grafana
  replicas: 1
  selector:
    matchLabels:
      app: ft_services
      tier: grafana
  template:
    metadata:
      labels:
        app: ft_services
        tier: grafana
    spec:
      containers:
      - name: grafana
        image: 42grafana
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
