apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin
  labels:
    app: ft_services
spec:
  selector:
    app: ft_services
    tier: phpmyadmin

  ports:
  - name: phpmyadmin
    port: 5000
  type: LoadBalancer

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: phpmyadmin
spec:
  serviceName: phpmyadmin
  replicas: 1
  selector:
    matchLabels:
      app: ft_services
      tier: phpmyadmin
  
  template:
    metadata:
      labels:
        app: ft_services
        tier: phpmyadmin
    
    spec:
      containers:
      - name: phpmyadmin
        image: 42phpmyadmin
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
