kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: ftp-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi

---
apiVersion: v1
kind: Service
metadata:
  name: ftps
  labels:
    app: ft_services
spec:
  selector:
    app: ft_services
    tier: ftps
  ports:
  - name: ftp
    port: 21
  - name: ftp-data
    port: 30000
  type: LoadBalancer

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ftps
spec:
  serviceName: ftps
  replicas: 1
  selector:
    matchLabels:
      app: ft_services
  template:
    metadata:
      labels:
        app: ft_services
        tier: ftps
    spec:
      volumes:
        - name: ftp-storage
          persistentVolumeClaim:
            claimName: ftp-claim
      containers:
      - name: ftps
        image: 42ftps
        imagePullPolicy: Never
        volumeMounts:
        - mountPath: "/home/pureftpd"
          name: ftp-storage
        ports:
        - containerPort: 21
        - containerPort: 30000
