kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mysql-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  selector:
    matchLabels: 
      type: local
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    app: ft_services
spec:
  selector:
    app: ft_services
    tier: mysql
  ports:
  - name: mysql
    port: 3306
  type: LoadBalancer

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
spec:
  serviceName: mysql
  replicas: 1
  selector:
    matchLabels:
      app: ft_services
      tier: mysql
  template:
    metadata:
      labels:
        app: ft_services
        tier: mysql
    spec:
      volumes:
        - name: mysql-storage
          persistentVolumeClaim:
            claimName: mysql-claim
      containers:
      - name: mysql
        image: 42mysql
        volumeMounts:
        - mountPath: "/var/lib/mysql"
          name: mysql-storage
        imagePullPolicy: Never
        ports:
        - containerPort: 3306
