kub delete --all deploy
kub delete --all statefulset
kub delete --all svc
kub delete --all nodes
kub delete --all pods
kub delete --all namespace
kub delete --all pvc
kub delete --all pv 
kub delete --all secrets
