apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: 42nginx
        imagePullPolicy: Never
        ports:
        - containerPort: 80
          name: http-port
        - containerPort: 443
          name: https-port
        env:
        - name: IP
          value: 10.0.2.15

---
  
apiVersion: v1
kind: Service
metadata:
  name: nginx
  annotations:
    metallb.universe.tf/allow-shared-ip: "sharing key"
spec:
  selector:
    app: nginx
  type: LoadBalancer
  loadBalancerIP: 10.0.2.15
  ports:
  - port: 80
    name: http-port
    targetPort: 80
    protocol: TCP
  - port: 443
    name: https-port
    targetPort: 443
    protocol: TCP    
