kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: ftp-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  selector:
    matchLabels: 
      type: local
---
apiVersion: v1
kind: Service
metadata:
  name: ftps
  annotations:
    metallb.universe.tf/allow-shared-ip: "sharing key"
  labels:
    app: ft_services
spec:
  type: LoadBalancer
  loadBalancerIP: ${EXTERNAL_IP}
  selector:
    app: ft_services
    tier: ftps
  ports:
  - name: ftp
    port: 21
  - name: ftp-data
    port: 30000


---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ftps
spec:
  serviceName: ftps
  replicas: 1
  selector:
    matchLabels:
      app: ft_services
  template:
    metadata:
      labels:
        app: ft_services
        tier: ftps
    spec:
      volumes:
        - name: ftp-storage
          persistentVolumeClaim:
            claimName: ftp-pvc
      containers:
      - name: ftps
        image: 42ftps
        imagePullPolicy: Never
        volumeMounts:
        - mountPath: "/home/vsftpd"
          name: ftp-storage
        ports:
        - containerPort: 21
        - containerPort: 30000
        env:
        - name: IP
          value: ${EXTERNAL_IP}
