apiVersion: v1
kind: Service
metadata:
  name: nginx
  annotations:
    metallb.universe.tf/allow-shared-ip: "sharing key"
  labels:
    app: ft_services
spec:
  type: LoadBalancer
  loadBalancerIP: ${EXTERNAL_IP}
  selector:
    app: ft_services
  ports:
  - name: http
    port: 80
  - name: https
    port: 443
  - name: ssh
    port: 22
---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nginx
spec:
  serviceName: nginx
  replicas: 1
  selector:
    matchLabels:
      app: ft_services
      tier: nginx
  template:
    metadata:
      labels:
        app: ft_services
        tier: nginx
    spec:
      containers:
      - name: nginx
        env:
        - name: IP
          value: ${EXTERNAL_IP}
        image: 42nginx
        imagePullPolicy: Never
        ports:
        - containerPort: 80

        
