apiVersion: v1
kind: Service
metadata:
  name: wordpress
  labels:
    app: ft_services
spec:
  selector:
    app: ft_services
    tier: wordpress
  ports:
  - name: wordpress
    port: 5050
  type: LoadBalancer

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: wordpress
spec:
  serviceName: wordpress
  replicas: 1
  selector:
    matchLabels:
      app: ft_services
      tier: wordpress
  template:
    metadata:
      labels:
        app: ft_services
        tier: wordpress
    spec:
      containers:
      - name: wordpress
        image: 42wordpress
        imagePullPolicy: Never
        ports:
        - containerPort: 5050

