apiVersion: v1
kind: Service
metadata:
  name: wordpress
  annotations:
    metallb.universe.tf/allow-shared-ip: "sharing key"
  labels:
    app: ft_services
spec:
  selector:
    app: ft_services
    tier: wordpress
  ports:
  - name: wordpress
    port: 5050
    targetPort: 5050
  type: LoadBalancer
  loadBalancerIP: ${EXTERNAL_IP}

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: wordpress
spec:
  serviceName: wordpress
  replicas: 1
  selector:
    matchLabels:
      app: ft_services
      tier: wordpress
  template:
    metadata:
      labels:
        app: ft_services
        tier: wordpress
    spec:
      containers:
      - name: wordpress
        image: 42wordpress
        env:
        - name: IP
          value: ${EXTERNAL_IP}
        imagePullPolicy: Never
        ports:
        - containerPort: 5050

